name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cjdilks/largex-eic:ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Test
        run: |
          source env.sh
          make
