name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cjdilks/largex-eic:ci
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Test
        run: |
          . env.sh
          make
