name: ci

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:

  build:
    runs-on: [ ubuntu-latest ]
    container:
      image: cjdilks/largex-eic:dev
      options: --user root

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Config
        run: source env.sh

      - name: Compile
        run: make

      - name: Macro Test
        run: |
          root -b -q container/ci/macro/analysis_xqbins.C
          root -b -q container/ci/macro/postprocess_xqbins_draw.C

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macro-test-images
          path: |
            out/macro.test.images
